import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import HeaderComponents from "@/components/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url('/images/cloudy/cloudy-2.jpg')] bg-center bg-cover bg-no-repeat h-screen`}>
        <HeaderComponents />
        <div>{children}</div>
      </body>
    </html>
  );
}
