"use client";

import { useEffect, useState } from "react";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import HeaderComponents from "@/components/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const imageName = window.localStorage.getItem("imageName");
// console.log(imageName);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [imageName, setImageName] = useState<string | null>("")

  useEffect(() => {
    const imageName = window.localStorage.getItem("imageName");
    setImageName(imageName)
  }, [setImageName])
  
  return (
    <html lang="en">
      <body
       style={{
        backgroundImage: `url(${imageName})`
      }}
        className={`${inter.className} bg-center bg-cover bg-no-repeat lg:h-screen w-screen`}
      >
        <HeaderComponents />
        <div>{children}</div>
      </body> 
    </html>
  );
}
// '/images/cloudy/cloudy-3.jpg'